'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dashboard = fs.readFileSync(path.join(root, 'assets', 'market-dashboard.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'assets', 'market-dashboard.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'articles', 'market.html'), 'utf8');
const amplifyRules = fs.readFileSync(path.join(root, 'infra', 'amplify-custom-rules.json'), 'utf8');

assert(html.includes('id="technical-range-navigator"'));
assert(html.includes('id="technical-range-navigator-slot"'));
assert(html.includes('id="technical-range-start"'));
assert(html.includes('id="technical-range-end"'));
assert(html.includes('id="technical-range-selection"'));
assert(html.includes('id="technical-range-overview"'));
assert(html.includes('class="technical-global-chart-controls"'));
assert(html.includes('id="technical-intraday-date"'));
assert.strictEqual((html.match(/data-kodex-chart-mode="daily"/g) || []).length, 1, '일봉·분봉 선택은 공통 네비게이터에 한 번만 있어야 한다.');
assert.strictEqual((html.match(/data-kodex-period="1m"/g) || []).length, 1, '일봉 조회 기간은 공통 네비게이터에 한 번만 있어야 한다.');
assert.strictEqual((html.match(/data-kodex-period="6m"/g) || []).length, 1, '일봉은 6개월 원자료까지 선택할 수 있어야 한다.');
assert(html.includes('data-kodex-period="6m" aria-pressed="true">6개월</button>'));
assert(html.includes('id="technical-range-start" class="technical-range-input is-start" type="range" min="0" max="100" step="1" value="50"'));
assert.strictEqual((html.match(/data-shared-intraday-date/g) || []).length, 1, '거래일 선택은 공통 네비게이터에 한 번만 있어야 한다.');
assert.strictEqual((html.match(/data-kodex-interval="5"/g) || []).length, 1, '분봉 간격 선택은 공통 네비게이터에 한 번만 있어야 한다.');
assert(!html.includes('id="kospi-intraday-date"'));
assert(!html.includes('id="kodex-intraday-date"'));
assert(dashboard.includes('var selectedKodexIntradayDateExplicit = false;'));
assert(dashboard.includes("var selectedKodexPeriod = '6m';"));
assert(dashboard.includes('var technicalRangeStart = 50;'));
assert(amplifyRules.includes('TQQQ?range=6mo&interval=1d'), 'TQQQ 일봉 원자료도 6개월이어야 한다.');
assert(dashboard.includes('selectedKodexIntradayDateExplicit = true;'));
assert(dashboard.includes('MarketDashboardLive.preferredIntradayDate(indexRows, selectedKodexIntradayDate, selectedKodexIntradayDateExplicit)'));
assert(dashboard.includes('if (kodex) setKodexChartControls(kodex);'));
assert(dashboard.includes('function technicalRangeSlice(rows)'));
assert(dashboard.includes('function updateTechnicalRangeNavigator(rows)'));
assert(dashboard.includes('function placeTechnicalRangeNavigator(stack)'));
assert(dashboard.includes("firstChart.insertAdjacentElement('afterend', slot)"));
assert(dashboard.includes('function updateFloatingDashboardControls()'));
assert(dashboard.includes('slotTop <= triggerTop'));
assert(dashboard.includes("navigator.classList.toggle('is-floating', shouldFloat)"));
assert(dashboard.includes("slot.classList.toggle('is-floating', shouldFloat)"));
assert(!dashboard.includes("slot.style.height = navigatorHeight + 'px'"), '플로팅 중 원래 슬롯 높이를 남기면 카드 사이에 빈 공간이 생긴다.');
assert(dashboard.includes("tabs.classList.toggle('is-floating'"));
assert(dashboard.includes("selection.addEventListener('pointermove'"));
assert(dashboard.includes("selection.addEventListener('keydown'"));
assert((dashboard.match(/technicalRangeSlice\(/g) || []).length >= 7, '모든 주요 기술적 차트가 공통 표시 범위를 사용해야 한다.');
assert(css.includes('.technical-range-navigator {'));
assert(css.includes('.technical-range-navigator.is-floating {\n    position: fixed;'));
assert(css.includes('.technical-range-navigator-slot {'));
assert(css.includes('.technical-range-navigator-slot.is-floating {\n    display: contents;'));
assert(css.includes('.market-view-tabs {\n    --market-tabs-sticky-top: 64px;\n    position: sticky;'));
assert(css.includes('.market-view-tabs.is-floating {'));
assert(css.includes('.technical-range-selection.is-dragging'));
assert(css.includes('.technical-range-input::-webkit-slider-thumb'));
assert(css.includes('.technical-global-chart-controls {'));
assert(css.includes('.technical-global-chart-controls [hidden] {\n    display: none !important;'));
assert(css.includes('padding-bottom: calc(var(--technical-navigator-height'));

const navigatorSlotIndex = html.indexOf('id="technical-range-navigator-slot"');
const firstChartEndIndex = html.indexOf('</section>', html.indexOf('data-technical-card="kospi-flow"'));
const nextCardIndex = html.indexOf('data-technical-card="kodex-technical"');
assert(firstChartEndIndex < navigatorSlotIndex && navigatorSlotIndex < nextCardIndex, '표시구간 네비게이터는 첫 차트 바로 뒤에 있어야 한다.');

console.log('Technical range navigator and live-date selection tests passed.');
