'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dashboard = fs.readFileSync(path.join(root, 'assets', 'market-dashboard.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'assets', 'market-dashboard.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'articles', 'market.html'), 'utf8');
const amplifyRules = fs.readFileSync(path.join(root, 'infra', 'amplify-custom-rules.json'), 'utf8');

assert(html.includes('id="technical-range-navigator"'));
assert(html.includes('id="technical-range-navigator-slot"'));
assert(html.includes('id="technical-range-start"'));
assert(html.includes('id="technical-range-end"'));
assert(html.includes('id="technical-range-selection"'));
assert(html.includes('id="technical-range-overview"'));
assert(html.includes('class="technical-global-chart-controls"'));
assert(html.includes('id="technical-intraday-date"'));
assert.strictEqual((html.match(/data-kodex-chart-mode="daily"/g) || []).length, 1, '일봉·분봉 선택은 공통 네비게이터에 한 번만 있어야 한다.');
assert.strictEqual((html.match(/data-kodex-period="1m"/g) || []).length, 1, '일봉 조회 기간은 공통 네비게이터에 한 번만 있어야 한다.');
assert.strictEqual((html.match(/data-kodex-period="1y"/g) || []).length, 1, '일봉은 1년 원자료까지 선택할 수 있어야 한다.');
assert(html.includes('data-kodex-period="1y" aria-pressed="true">1년</button>'));
assert(html.includes('id="technical-range-start" class="technical-range-input is-start" type="range" min="0" max="100" step="1" value="50"'));
assert.strictEqual((html.match(/data-shared-intraday-date/g) || []).length, 1, '거래일 선택은 공통 네비게이터에 한 번만 있어야 한다.');
assert.strictEqual((html.match(/data-kodex-interval="5"/g) || []).length, 1, '분봉 간격 선택은 공통 네비게이터에 한 번만 있어야 한다.');
assert(!html.includes('id="kospi-intraday-date"'));
assert(!html.includes('id="kodex-intraday-date"'));
assert(dashboard.includes('var selectedKodexIntradayDateExplicit = false;'));
assert(dashboard.includes("var selectedKodexPeriod = '1y';"));
assert(dashboard.includes('var technicalRangeStart = 50;'));
assert(dashboard.includes("var technicalChartStateStorageKey = 'hpmplab-technical-chart-state-v1';"));
assert(dashboard.includes('function restoreTechnicalChartState()'));
assert(dashboard.includes('function persistTechnicalChartState()'));
assert(dashboard.includes('restoreTechnicalChartState();'));
assert(dashboard.includes('window.localStorage.getItem(technicalChartStateStorageKey)'));
assert(dashboard.includes('window.localStorage.setItem(technicalChartStateStorageKey, serialized)'));
assert(dashboard.includes('intradayDateExplicit: Boolean(date && source.intradayDateExplicit)'));
assert(dashboard.includes('selectedKodexIntradayDateExplicit = false;'), '새 페이지에서는 전 거래일 직접 선택 상태를 이어받지 않아야 한다.');
assert((dashboard.match(/persistTechnicalChartState\(\);/g) || []).length >= 6, '모드·기간·분 간격·거래일·표시 구간 선택을 저장해야 한다.');
assert(dashboard.includes('if (dates.length && preferredDate !== selectedKodexIntradayDate) {'), '초기 날짜 목록이 비어 있을 때 저장된 거래일을 덮어쓰면 안 된다.');
assert(dashboard.includes("document.querySelectorAll('.kodex-history-shell, .leading-cycle-shell')"), '가로 스크롤이 필요한 시계열 차트를 한 경로에서 관리해야 한다.');
assert(dashboard.includes('function alignTechnicalChartsToLatest(force)'));
assert(dashboard.includes('shell.scrollLeft = maximum;'), '좁은 화면의 첫 진입은 최신 시점인 오른쪽 끝을 보여줘야 한다.');
assert(dashboard.includes("data-latest-scroll-user-away', maximum - shell.scrollLeft > 32 ? 'true' : 'false'"), '사용자가 과거 구간을 보고 있으면 자동 스크롤을 멈춰야 한다.');
assert(dashboard.includes("observer.observe(chart, { childList: true });"), '비동기 데이터 렌더로 차트 폭이 늘어난 뒤 최신 시점을 다시 맞춰야 한다.');
assert(dashboard.includes('function resetTechnicalChartHorizontalScroll()'));
assert((dashboard.match(/resetTechnicalChartHorizontalScroll\(\);/g) || []).length >= 4, '모드·기간·분 간격·거래일 변경 시 최신 시점으로 다시 맞춰야 한다.');
assert(amplifyRules.includes('TQQQ?range=2y&interval=1d'), 'TQQQ 일봉은 1년 표시 앞의 지표 계산 구간까지 확보해야 한다.');
assert(amplifyRules.includes('count=360'), 'KOSPI 일봉은 1년 표시 앞의 60봉 계산 구간까지 확보해야 한다.');
assert(amplifyRules.includes('/market-data/stock/122630/history/price-7'), 'KODEX 일봉은 1년 표시 앞의 지표 계산 구간까지 페이지를 확장해야 한다.');
assert(dashboard.includes('var intradayNavigatorSessionCount = 4;'));
assert(dashboard.includes('var intradayIndicatorWarmupSessionCount = 14;'));
assert(dashboard.includes('function intradayDisplayRows(rows, day)'));
assert(dashboard.includes('function intradayCalculationDays(primaryDays, warmupDays, targetDate)'));
assert(amplifyRules.includes('/market-data/index/KOSPI/intraday-warmup'));
assert(amplifyRules.includes('/market-data/stock/122630/intraday-warmup'));
assert(dashboard.includes('function effectiveIntradayInterval(day, requestedInterval)'));
assert(dashboard.includes("return [1, 5, 15, 30, 60].indexOf(requested) !== -1 ? requested : 5;"), '네비게이터 표시 폭이 넓어져도 사용자가 고른 분 간격을 자동 변경하면 안 된다.');
assert(!dashboard.includes('rawCount * visibleRatio / value <= maxIntradayRenderedBars'), '표시 구간에 따라 1분 선택을 5분으로 자동 승격하면 안 된다.');
const intradaySummaryStart = dashboard.indexOf('function renderKodexIntradayRows');
const intradaySummaryEnd = dashboard.indexOf('function renderKodexIntradayChart', intradaySummaryStart);
const intradaySummaryBody = dashboard.slice(intradaySummaryStart, intradaySummaryEnd);
assert(intradaySummaryBody.includes("summary.classList.add('is-intraday-compact')"));
['수익률', '거래량', '추정 순압력', 'CVD'].forEach(function (label) {
    assert(intradaySummaryBody.includes("appendKodexMetric(summary, '" + label + "'"), label + ' 한 줄 지표가 필요하다.');
});
['표시 구간', '봉 간격', '오늘 수익률', '오늘 거래량', '오늘 추정 순압력', '오늘 CVD'].forEach(function (label) {
    assert(!intradaySummaryBody.includes("appendKodexMetric(summary, '" + label + "'"), label + ' 지표는 제거해야 한다.');
});
assert(dashboard.includes('selectedKodexIntradayDateExplicit = true;'));
assert(dashboard.includes('MarketDashboardLive.preferredIntradayDate(indexRows, selectedKodexIntradayDate, selectedKodexIntradayDateExplicit)'));
assert(dashboard.includes('if (kodex) setKodexChartControls(kodex);'));
assert(dashboard.includes('function technicalRangeSlice(rows)'));
assert(dashboard.includes('function updateTechnicalRangeNavigator(rows)'));
assert(dashboard.includes('function placeTechnicalRangeNavigator(stack)'));
assert(dashboard.includes("firstChart.insertAdjacentElement('afterend', slot)"));
assert(dashboard.includes('function updateFloatingDashboardControls()'));
assert(dashboard.includes('slotTop <= triggerTop'));
assert(dashboard.includes("navigator.classList.toggle('is-floating', shouldFloat)"));
assert(dashboard.includes("slot.classList.toggle('is-floating', shouldFloat)"));
assert(!dashboard.includes("slot.style.height = navigatorHeight + 'px'"), '플로팅 중 원래 슬롯 높이를 남기면 카드 사이에 빈 공간이 생긴다.');
assert(dashboard.includes("tabs.classList.toggle('is-floating'"));
assert(dashboard.includes("selection.addEventListener('pointermove'"));
assert(dashboard.includes("selection.addEventListener('keydown'"));
assert(dashboard.includes("setTechnicalRange(Math.min(Number(startInput.value), technicalRangeEnd - 5), technicalRangeEnd, false)"));
assert(dashboard.includes("setTechnicalRange(technicalRangeStart, Math.max(Number(endInput.value), technicalRangeStart + 5), false)"));
assert(dashboard.includes('var technicalRangePreviewInterval = 48;'), '드래그 중 차트 미리보기는 전체 프레임을 점유하지 않도록 제한해야 한다.');
assert(dashboard.includes('function technicalCardNearViewport(cardId)'), '화면에 보이는 기술 차트만 미리보기로 갱신해야 한다.');
assert(dashboard.includes('function renderTechnicalRangePreview()'));
assert(dashboard.includes('function queueTechnicalRangePreview()'));
assert((dashboard.match(/queueTechnicalRangePreview\(\);/g) || []).length >= 3, '두 핸들과 구간 이동 모두 실시간 차트 미리보기를 요청해야 한다.');
const previewStart = dashboard.indexOf('function renderTechnicalRangePreview()');
const previewEnd = dashboard.indexOf('function queueTechnicalRangePreview()', previewStart);
const previewBody = dashboard.slice(previewStart, previewEnd);
assert(previewBody.includes("technicalCardNearViewport('kospi-flow')"));
assert(previewBody.includes("technicalCardNearViewport('kodex-history')"));
assert(previewBody.includes("technicalCardNearViewport('composite-momentum')"));
assert(previewBody.includes("technicalCardNearViewport('tqqq-history')"));
assert(!previewBody.includes('renderLeadingCycleComparison'), '표시 구간과 무관한 장기 선행지수 카드는 드래그 중 다시 그리면 안 된다.');
assert(!previewBody.includes('fetchKospiIntradayDay'), '분봉 핸들 미리보기에서 네트워크 요청을 시작하면 안 된다.');
assert(!previewBody.includes('renderKospiIntradayChart()'), '분봉 핸들 미리보기는 마지막 렌더 데이터를 직접 사용해야 한다.');
assert(!previewBody.includes('renderKodexIntradayChart('), 'KODEX 분봉 미리보기는 마지막 렌더 데이터를 직접 사용해야 한다.');
assert(dashboard.includes("startInput.addEventListener('change', queueTechnicalRangeRender)"));
assert(dashboard.includes("endInput.addEventListener('change', queueTechnicalRangeRender)"));
assert((dashboard.match(/technicalRangeSlice\(/g) || []).length >= 7, '모든 주요 기술적 차트가 공통 표시 범위를 사용해야 한다.');
assert(css.includes('.technical-range-navigator {'));
assert(css.includes('.technical-range-navigator.is-floating {\n    position: fixed;'));
assert(css.includes('.technical-range-navigator-slot {'));
assert(css.includes('.technical-range-navigator-slot.is-floating {\n    display: contents;'));
assert(css.includes('.market-view-tabs {\n    --market-tabs-sticky-top: 64px;\n    position: sticky;'));
assert(css.includes('.market-view-tabs.is-floating {'));
assert(css.includes('.technical-range-selection.is-dragging'));
assert(css.includes('.technical-range-input::-webkit-slider-thumb'));
assert(css.includes('backdrop-filter: none'));
assert(css.includes('.technical-global-chart-controls {'));
assert(css.includes('.technical-global-chart-controls [hidden] {\n    display: none !important;'));
assert(css.includes('.kodex-history-summary.is-intraday-compact {'));
assert(css.includes('white-space: nowrap;'), '분봉 지표는 한 줄을 유지해야 한다.');
assert(css.includes('padding-bottom: calc(var(--technical-navigator-height'));

const navigatorSlotIndex = html.indexOf('id="technical-range-navigator-slot"');
const firstChartEndIndex = html.indexOf('</section>', html.indexOf('data-technical-card="kospi-flow"'));
const nextCardIndex = html.indexOf('data-technical-card="leading-cycle-comparison"');
assert(firstChartEndIndex < navigatorSlotIndex && navigatorSlotIndex < nextCardIndex, '표시구간 네비게이터는 첫 차트 바로 뒤에 있어야 한다.');

console.log('Technical range navigator and live-date selection tests passed.');
